global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: "bitburner-prom"

scrape_configs:
- job_name: "bitburner"
  scrape_interval: 1s

  static_configs:
  - targets: [ "desktop-sol.lan:8888" ]
  